version: "3.9"

services:
  satisatang-postgres:
    image: postgres:16
    container_name: satisatang-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - satisatang_postgres_data:/var/lib/postgresql/data

volumes:
  satisatang_postgres_data: