version: "3.9"

services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - ${FRONTEND_PORT}:5173
    depends_on:
      - backend
  backend:
    build: ./backend
    restart: unless-stopped

    env_file:
      - ./backend/.env.local
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - ${BACKEND_PORT}:8080
    depends_on:
      - postgres
      - minio
      - qdrant

  python-cron:
    build: ./cron
    container_name: python-cron
    restart: unless-stopped
    volumes:
      - ./cron:/app
    env_file:
      - ./cron/.env.local
    environment:
      - TZ=Asia/Bangkok
    depends_on:
      - backend
      - postgres
      - minio
      - qdrant

  postgres:
    image: postgres:16
    container_name: satisatang-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - satisatang_postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: satisatang-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    command: server /data --console-address ":9001"
    volumes:
      - satisatang_minio_data:/data

  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: satisatang-qdrant
    ports:
      - "${QDRANT_PORT}:6333"
    volumes:
      - satisatang_qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  satisatang_postgres_data:
  satisatang_minio_data:
  satisatang_qdrant_data:
