version: '3.8'
name: SatiSatang
services:
  db:
    build:
      context: ../db
      dockerfile: dockerfile
    container_name: satisatang-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - satisatang_postgres_data:/var/lib/postgresql
    networks:
      - satisatang-network

  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: satisatang-qdrant
    volumes:
      - satisatang_qdrant_data:/qdrant/storage
    ports:
      - "${QDRANT_PORT}:6333"
    restart: unless-stopped
    networks:
      - satisatang-network

  redis:
    image: redis:7
    container_name: satisatang-redis
    restart: unless-stopped
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - satisatang_redis_data:/data
    networks:
      - satisatang-network

networks:
  satisatang-network:
    driver: bridge

volumes:
  satisatang_qdrant_data:
  satisatang_redis_data:
  satisatang_postgres_data:


