name: SatiSatang
services:

  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: satisatang-qdrant
    volumes:
      - satisatang_qdrant_data:/qdrant/storage
    ports:
      - "${QDRANT_PORT}:6333"
    restart: unless-stopped
    networks:
      - satisatang-network

  redis:
    image: redis:7
    container_name: satisatang-redis
    restart: unless-stopped
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - satisatang_redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - satisatang-network

networks:
  satisatang-network:
    driver: bridge

volumes:
  satisatang_qdrant_data:
  satisatang_redis_data:


