BEGIN;

INSERT INTO icons (url, description, user_id, created_at, updated_at)
VALUES
    ('icons/system-food.png', 'อาหาร ของกิน ข้าว มื้อเช้า มื้อเที่ยง มื้อเย็น หิว food meal eat rice', NULL, NOW(), NOW()),
    ('icons/system-burger.png', 'เบอร์เกอร์ ฟาสต์ฟู้ด ขนมปัง อเมริกัน จานด่วน burger fastfood bread', NULL, NOW(), NOW()),
    ('icons/system-noodle.png', 'ก๋วยเตี๋ยว เส้น บะหมี่ ราเมง อาหารญี่ปุ่น noodle ramen soup', NULL, NOW(), NOW()),
    ('icons/system-coffee.png', 'กาแฟ คาเฟ่ เครื่องดื่ม น้ำหวาน ชานม สตาร์บัค อเมซอน', NULL, NOW(), NOW()),
    ('icons/system-beer.png', 'เบียร์ เหล้า แอลกอฮอล์ ปาร์ตี้ สังสรรค์ บาร์ beer alcohol ', NULL, NOW(), NOW()),
    ('icons/system-dessert.png', 'ขนม หวาน เค้ก ไอศครีม เบเกอรี่ ของว่าง dessert sweet cake bakery', NULL, NOW(), NOW()),
    ('icons/system-car.png', 'รถยนต์ เดินทาง ค่าน้ำมัน ทางด่วน ซ่อมรถ ล้างรถ car transport gas drive', NULL, NOW(), NOW()),
    ('icons/system-bus.png', 'รถเมล์ รถบัส ขนส่งสาธารณะ ตั๋วรถ bus public transport ticket', NULL, NOW(), NOW()),
    ('icons/system-train.png', 'รถไฟ BTS MRT รถไฟฟ้า ตั๋วรถไฟ train subway transport', NULL, NOW(), NOW()),
    ('icons/system-taxi.png', 'แท็กซี่ แกร็บ เรียกรถ ค่ารถ taxi grab transport cab', NULL, NOW(), NOW()),
    ('icons/system-plane.png', 'เครื่องบิน ท่องเที่ยว ตั๋วเครื่องบิน ต่างประเทศ สนามบิน airplane', NULL, NOW(), NOW()),
    ('icons/system-home.png', 'บ้าน ที่พัก ค่าเช่า ผ่อนบ้าน คอนโด แต่งบ้าน house home rent condo', NULL, NOW(), NOW()),
    ('icons/system-water.png', 'ค่าน้ำ ประปา บิล จ่ายบิล water bill utility', NULL, NOW(), NOW()),
    ('icons/system-electric.png', 'ค่าไฟ ไฟฟ้า บิล แอร์ พัดลม electric bill power utility', NULL, NOW(), NOW()),
    ('icons/system-wifi.png', 'เน็ต ค่าโทรศัพท์ มือถือ อินเทอร์เน็ต เติมเงิน wifi internet phone', NULL, NOW(), NOW()),
    ('icons/system-maintenance.png', 'ซ่อมแซม ค่าแรง ช่าง อุปกรณ์ เครื่องมือ repair fix tool', NULL, NOW(), NOW()),
    ('icons/system-shopping.png', 'ช้อปปิ้ง ซื้อของ ห้าง จ่ายตลาด ตลาดนัด shopping buy mall market', NULL, NOW(), NOW()),
    ('icons/system-clothes.png', 'เสื้อผ้า แฟชั่น แต่งตัว กางเกง กระเป๋า รองเท้า clothes fashion wear', NULL, NOW(), NOW()),
    ('icons/system-makeup.png', 'เครื่องสำอาง ความงาม สวยงาม สกินแคร์ makeup beauty skincare cosmetic', NULL, NOW(), NOW()),
    ('icons/system-device.png', 'ไอที คอมพิวเตอร์ มือถือ แกดเจ็ต อุปกรณ์อิเล็กทรอนิกส์ device gadget', NULL, NOW(), NOW()),
    ('icons/system-hospital.png', 'โรงพยาบาล หาหมอ เจ็บป่วย รักษา hospital doctor sick medical', NULL, NOW(), NOW()),
    ('icons/system-pill.png', 'ยา ค่ายา วิตามิน อาหารเสริม ร้านขายยา medicine pill drug pharmacy', NULL, NOW(), NOW()),
    ('icons/system-gym.png', 'ออกกำลังกาย ฟิตเนส ยิม กีฬา สุขภาพ gym fitness sport exercise health', NULL, NOW(), NOW()),
    ('icons/system-movie.png', 'ดูหนัง ภาพยนตร์ Netflix โรงหนัง ตั๋วหนัง movie cinema film netflix', NULL, NOW(), NOW()),
    ('icons/system-game.png', 'เกม เติมเกม ของเล่น สนุก game toy play fun', NULL, NOW(), NOW()),
    ('icons/system-pet.png', 'สัตว์เลี้ยง หมา แมว อาหารเม็ด pet dog cat animal food', NULL, NOW(), NOW()),
    ('icons/system-book.png', 'หนังสือ การเรียน คอร์สเรียน สมุด เครื่องเขียน book study learn', NULL, NOW(), NOW()),
    ('icons/system-gift.png', 'ของขวัญ งานแต่ง งานบวช ใส่ซอง gift present wedding', NULL, NOW(), NOW()),
    ('icons/system-salary.png', 'เงินเดือน รายรับ เงินเข้า โบนัส จ่ายเงิน salary income money bonus', NULL, NOW(), NOW()),
    ('icons/system-wallet.png', 'กระเป๋าตังค์ เงินสด ถอนเงิน เก็บเงิน wallet cash money save', NULL, NOW(), NOW()),
    ('icons/system-bank.png', 'ธนาคาร ดอกเบี้ย ฝากเงิน โอนเงิน bank interest transfer', NULL, NOW(), NOW()),
    ('icons/system-invest.png', 'ลงทุน หุ้น กองทุน คริปโต กำไร ขาดทุน invest stock crypto trade', NULL, NOW(), NOW())
ON CONFLICT (url) DO NOTHING;

INSERT INTO categories (name, type, user_id, icon_id, created_at, updated_at, deleted_at)
VALUES
    ('อาหาร', 'EXPENSE', NULL, (SELECT id FROM icons WHERE url = 'icons/system-food.png' LIMIT 1), NOW(), NOW(), NULL),
    ('เดินทาง', 'EXPENSE', NULL, (SELECT id FROM icons WHERE url = 'icons/system-car.png' LIMIT 1), NOW(), NOW(), NULL),
    ('ที่พัก/ของใช้', 'EXPENSE', NULL, (SELECT id FROM icons WHERE url = 'icons/system-home.png' LIMIT 1), NOW(), NOW(), NULL),
    ('น้ำ/ไฟ/เน็ต', 'EXPENSE', NULL, (SELECT id FROM icons WHERE url = 'icons/system-electric.png' LIMIT 1), NOW(), NOW(), NULL),
    ('ช้อปปิ้ง', 'EXPENSE', NULL, (SELECT id FROM icons WHERE url = 'icons/system-shopping.png' LIMIT 1), NOW(), NOW(), NULL),
    ('บันเทิง', 'EXPENSE', NULL, (SELECT id FROM icons WHERE url = 'icons/system-movie.png' LIMIT 1), NOW(), NOW(), NULL),
    ('สุขภาพ', 'EXPENSE', NULL, (SELECT id FROM icons WHERE url = 'icons/system-hospital.png' LIMIT 1), NOW(), NOW(), NULL),
    ('เงินเดือน', 'INCOME', NULL, (SELECT id FROM icons WHERE url = 'icons/system-salary.png' LIMIT 1), NOW(), NOW(), NULL),
    ('โบนัส', 'INCOME', NULL, (SELECT id FROM icons WHERE url = 'icons/system-gift.png' LIMIT 1), NOW(), NOW(), NULL),
    ('งานเสริม/ค้าขาย', 'INCOME', NULL, (SELECT id FROM icons WHERE url = 'icons/system-device.png' LIMIT 1), NOW(), NOW(), NULL),
    ('การลงทุน/ดอกเบี้ย', 'INCOME', NULL, (SELECT id FROM icons WHERE url = 'icons/system-invest.png' LIMIT 1), NOW(), NOW(), NULL),
    ('โชคลาภ/ของขวัญ', 'INCOME', NULL, (SELECT id FROM icons WHERE url = 'icons/system-gift.png' LIMIT 1), NOW(), NOW(), NULL),
    ('เงินคืน', 'INCOME', NULL, (SELECT id FROM icons WHERE url = 'icons/system-wallet.png' LIMIT 1), NOW(), NOW(), NULL);

INSERT INTO public.stocks (symbol, name, quote_type, currency, market, last_updated, created_at, updated_at)
VALUES
    ('AOT.BK', 'Airports of Thailand', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('AWC.BK', 'Asset World Corp', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('BANPU.BK', 'Banpu', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('BBL.BK', 'Bangkok Bank', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('BCP.BK', 'Bangchak Corporation', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('BDMS.BK', 'Bangkok Dusit Medical Service', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('BEM.BK', 'Bangkok Expressway and Metro', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('BH.BK', 'Bumrungrad International Hospital', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('BJC.BK', 'Berli Jucker', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('BTS.BK', 'BTS Group Holdings', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('CBG.BK', 'Carabao Group', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('CCET.BK', 'Cal-Comp Electronics (Thailand)', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('COM7.BK', 'Com Seven', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('CPALL.BK', 'CP All', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('CPF.BK', 'Charoen Pokphand Foods', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('CPN.BK', 'Central Pattana', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('CRC.BK', 'Central Retail Corporation', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('DELTA.BK', 'Delta Electronics (Thailand)', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('EA.BK', 'Energy Absolute', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('GULF.BK', 'Gulf Development', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('HMPRO.BK', 'Home Product Center', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('IVL.BK', 'Indorama Ventures', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('IRPC.BK', 'IRPC', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('KBANK.BK', 'Kasikornbank', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('KCE.BK', 'KCE Electronics', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('KKP.BK', 'Kiatnakin Phatra Bank', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('KTB.BK', 'Krungthai Bank', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('KTC.BK', 'Krungthai Card', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('LH.BK', 'Land and Houses', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('MINT.BK', 'Minor International', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('MTC.BK', 'Muangthai Capital', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('OR.BK', 'PTT Oil and Retail Business', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('OSP.BK', 'Osotspa', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('PTTGC.BK', 'PTT Global Chemical', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('RATCH.BK', 'Ratch Group', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('SCGP.BK', 'SCG Packaging', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('SAWAD.BK', 'Srisawad Corporation', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('SCC.BK', 'Siam Cement', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('SCB.BK', 'Siam Commercial Bank', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('TIDLOR.BK', 'TIDLOR', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('TISCO.BK', 'Tisco Financial Group', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('TU.BK', 'Thai Union Group', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW()),
    ('TOP.BK', 'Thai Oil', 'Equity', 'THB', 'SET', NOW(), NOW(), NOW())
ON CONFLICT (symbol) DO UPDATE 
SET 
    name = EXCLUDED.name,
    quote_type = EXCLUDED.quote_type,
    currency = EXCLUDED.currency,
    market = EXCLUDED.market,
    last_updated = EXCLUDED.last_updated,
    updated_at = EXCLUDED.updated_at;

COMMIT;